[mgr]
sort_by = "extension"
sort_dir_first = true
linemode = "size"
show_hidden = true
mouse_events = ["click", "scroll", "touch", "move", "drag"]

[opener]
edit = [
    { run = 'nvim "$@"', block = true, desc = "Edit with Neovim" }
]
